### ISSUE TITLE
RuntimeException on launch

### ISSUE THREAD

**Issue by ze42** [zend-patterns/ZendServerSDK#51]
I have a host (note for self: host328) on which we get a RuntimeException when trying to launch the script. It just fails to load and do anything useful.

```
# php /usr/local/lib/xxx/zendserver/zs-client.phar command:help

Fatal error: Uncaught exception 'Zend\Stdlib\Exception\RuntimeException' with message 'glob('config/autoload/{,*.}{global,local}.php', 1024) failed' in phar:///usr/local/lib/xxx/zendserver/zs-client.phar/vendor/zendframework/zend-stdlib/Zend/Stdlib/Glob.php:2
Stack trace:
#0 phar:///usr/local/lib/xxx/zendserver/zs-client.phar/vendor/zendframework/zend-stdlib/Zend/Stdlib/Glob.php(2): Zend\Stdlib\Glob::systemGlob('config/autoload...', 16)
#1 phar:///usr/local/lib/xxx/zendserver/zs-client.phar/vendor/zendframework/zend-modulemanager/Zend/ModuleManager/Listener/ConfigListener.php(2): Zend\Stdlib\Glob::glob('config/autoload...', 16)
#2 phar:///usr/local/lib/xxx/zendserver/zs-client.phar/vendor/zendframework/zend-modulemanager/Zend/ModuleManager/Listener/ConfigListener.php(2): Zend\ModuleManager\Listener\ConfigListener->addConfigByPath('config/autoload...', 'glob_path')
#3 [internal function]: Zend\ModuleManager\Listener\ConfigListener->onLoadModulesPost(Object(Zend\ModuleManager\ModuleEvent))
#4 phar:///usr/local/lib/xxx/zends in phar:///usr/local/lib/xxx/zendserver/zs-client.phar/vendor/zendframework/zend-stdlib/Zend/Stdlib/Glob.php on line 2
```

Any idea what could cause such error, or how to investigate further?

**Comment by slaff** [comment]
If there is more detailed information we can reopen this issue.
